version: "3"
services:
    db:
        image: redis:latest
        restart: always
        volumes:
            - ./redis:/app/redis
        command: redis-server /app/redis/redis.conf
        network_mode: host
        ports:
            - 6379:6379
